### ISSUE TITLE
:where selector did not work for us

### ISSUE THREAD

**Issue by luxterful** [Roman86/tailwindcss-scoped-preflight#1]
Hi, 
thank you very much for this plugin.
Unfortunately the `:where` selector did not work for us.

I have changed the line where the selector is set to ```return `${cssSelector} ${s}`;``` and this actually works pretty well.

Is there any reason why you are using `:where` over wrapping the style with a class name in front of it?

**Comment by Roman86** [comment]
Hi @luxterful ! Thanks for using it and reaching out! Yes, there are reasons to use `:where`. Your fix requires another DOM-element - the wrapper. While `:where` allows you to mark you element directly without extra wrappers.
What browser (and version) do you use? Please provide some simplified piece of your DOM structure so I could investigate more on it.

**Comment by Roman86** [comment]
@luxterful please chime in and reopen with some example and answers so I could investigate. Closing for now.
If anybody has the same issue - I could add another mode that works in a way mentioned by @luxterful
