### ISSUE TITLE
.container not scoped ?

### ISSUE THREAD

**Issue by yabdab** [Roman86/tailwindcss-scoped-preflight#17]
Started using this and it is Great! 

Only problem I am having is that .container is not getting scoped?

If this a known thing or am I missing something?

```javascript
 plugins: [
    scopedPreflightStyles({
      isolationStrategy: isolateInsideOfContainer(".my-form"),
    }),
...
]
````

**Comment by Roman86** [comment]
Hi @yabdab ! I believe `isolateForComponents` strategy is the one you're looking for. Just import it instead of `isolateInsideOfContainer`.
See [https://github.com/Roman86/tailwindcss-scoped-preflight?tab=readme-ov-file#strategies-overview](images) describing how strategies differ.

**Comment by yabdab** [comment]
No, I still want to isolate inside my specified class.
 
The problem is, since .container is not protected, the styling from tailwindcss effects the styling of `.container `from Foundation.

I only want tailwind to style  `.container`  if it is inside `.my-form`

Hope that makes sense?

**Comment by yabdab** [comment]
Since I do not use taillwind's `.container` I decided to just not include that plugin using my config.

```json
module.exports = {
  corePlugins: {
    container: false,
  },
...
}
```

Although it would have been nice to have `.container:where(.my-form,.my-form *)` instead.

Otherwise, BIG THANKS to @Roman86 for making this , it works great except for my fringe issue.

**Comment by Roman86** [comment]
it has nothing to do with container option. Maybe don't completely understand. Just try the strategy I mentioned (isolateForComponents) - it isolates Tailwind styles for every element that has specified css selector (your button or common class).

**Comment by Roman86** [comment]
actually if you use `isolateInsideOfContainer(".my-form")` - then `.container` outside of `.my-form` can't be affected by the **preflight** styles (which is this plugin about), see the picture. BUT - your container is affected by the container plugin, which is unrelated to the preflight styles, but I feel like you (and other users) expect this issue to be addressed as well. I'm thinking about a good way to cover this

![image](https://github.com/Roman86/tailwindcss-scoped-preflight/assets/6422343/cf630304-914e-4f1e-abe5-804f81710953)

<img width="252" alt="image" src="https://github.com/Roman86/tailwindcss-scoped-preflight/assets/6422343/2de31225-d7d3-4e2b-bb2d-625a5b2de1c0">

**Comment by Roman86** [comment]
> Since I do not use taillwind's `.container` I decided to just not include that plugin using my config.
> 
> ```json
> module.exports = {
>   corePlugins: {
>     container: false,
>   },
> ...
> }
> ```

Seems like what you did is the best. That `.container` selector is hardcoded in the Tailwind's codebase, not configurable. Trying to deal with this particular issue may open a can of worms as more plugins may exist that affect global styles, probably they should be addressed to dedicated tools or postcss plugins
