### ISSUE TITLE
Import errors with Vite??

### ISSUE THREAD

**Issue by OluAgunloye** [Roman86/tailwindcss-scoped-preflight#2]
Error:
`.../node_modules/tailwindcss-scoped-preflight/dist/plugin.mjs not supported.
Instead change the require of .../node_modules/tailwindcss-scoped-preflight/dist/plugin.mjs to a dynamic import() which is available in all CommonJS modules.`

**Comment by OluAgunloye** [comment]
This works just fine so long as your tailwind and postcss config files are pure js not cjs btw.

**Comment by Roman86** [comment]
@OluAgunloye could you please share a minimal reproducible project boilerplate so I could play with it?

[I just made one with vite](https://github.com/Roman86/tailwindcss-scoped-preflight-vite-ts-sample) - out of the box I had issue with postcss until changed the provided package.json "type" from "module" to "commonjs". The plugin is installing and working just fine. Readme there is generic, you may ignore it - just checkout, install dependencies and run.

**Comment by Roman86** [comment]
@OluAgunloye just released [v1.2.0](https://github.com/Roman86/tailwindcss-scoped-preflight/compare/v2.0.3...v2.1.0) - it may resolve the require issue, if it's your case. Please check

**Comment by Roman86** [comment]
as mentioned 3 weeks ago, it should have been fixed, closing for now. @OluAgunloye Please try the new version and if it doesn't fix your issue - feel free to reopen but provide a minimal reproducible project with your case
