### ISSUE TITLE
Preflight parts of the components

### ISSUE THREAD

**Issue by Muchaszewski** [Roman86/tailwindcss-scoped-preflight#21]
**Is your feature request related to a problem? Please describe.**
I have my page using tailwind as usual, but want import single page with preflight enabled, but then i wans single components inside of the preflight to use default tailwind styling

**Describe the solution you'd like**
```
<p>Styled with tailwindcss</p>
<div className=".twr"> <- enable preflight
   <p>Some Content</p>
   <a className=".twe">Link</a> <- disable preflight just for this component
   <p>Continue as usual</p>
</div>
<p>Styled with tailwindcss</p>
```

**Describe alternatives you've considered**
Manualy style each component to look like preflight or custom isolation strategy, but the configuration seems to convoluted to implement

**Comment by Roman86** [comment]
Hi @Muchaszewski ! Thanks for reaching out. May I ask a question about your demo code: you want to enable preflight for `.twp` only, while the sibling `<p>` elements are styles with Tailwind also. Shouldn't they also be under the preflight? If yes - then `isolateOutsideOfContainer` could do this job:
```ts
    scopedPreflightStyles({
      isolationStrategy: isolateOutsideOfContainer('.twe'),
    }),
```

Otherwise I can help you with a custom strategy

**Comment by Muchaszewski** [comment]
I will use my logic here and that may explain the ticket I created it might help understand the example I gave.

**NOTE:** I noticed that I mixed up what preflight is and assumed it's browser styling. That's where confusion might have come.

Preflight is a bunch of styles that are applied by default to all pages by tailwind to remove browser styling. With your plugin I can (as you mentioned above) use the config to apply "disable" preflight to all components with this class and it's children.

I wanted to mix preflight and non-preflight components. The `isolateOutsideOfContainer` works as intended, but the custom components inside this preflight-disabled component are all over the place, because I do not override all preflight styles in my custom component.

The example I provided above assumes that `.twr` was using `isolateOutsideOfContainer` and `.twe` enabled preflight for the component.

**Real-world use case:**
I wanted to import some raw HTML files into my page from some generator, and style it as is using preflight-disabled config. All good here, and your plugin works perfectly!
Then I have a few custom components that I want to inject into this component (CTAs, Context, Tooltips etc.) and given that preflight is now disabled for this component, all my custom components are broken, and I either have to style them with preflight-disabled in mind, or hope your plugin will provide this functionality :)

**Comment by Roman86** [comment]
thanks for your clarification. So it seems like you want preflight to be outside of that custom HTML, but still have it for some component inside of that excluded area. If we imagine some set A (the whole webpage) and its subset B (your external HTML) and its subset C (your custom components in it) - you want A and C to be preflighted, but not B. Correct?

**Comment by Muchaszewski** [comment]
Correct!

**Comment by Roman86** [comment]
I'm adding options to existing strategies so it's possible to handle extra cases. Like this:
```ts
    scopedPreflightStyles({
      isolationStrategy: isolateOutsideOfContainer('.no-tw', {
        plus: '.tw',
      }),
    }),
```

```ts
    scopedPreflightStyles({
      isolationStrategy: isolateInsideOfContainer('.tw', {
        except: '.no-tw',
      }),
    }),
```

**Comment by Roman86** [comment]
@Muchaszewski try
```bash
npm i -D tailwindcss-scoped-preflight@beta
```
