### ISSUE TITLE
`:where` selector not working on Safari 15.2

### ISSUE THREAD

**Issue by PhilipHow** [Roman86/tailwindcss-scoped-preflight#3]
First off - thanks for this plugin - it's really useful!

I'm running into issues on Safari, where I just can't see the `*:where` selector being processed at all. This means that the `border-style` is not being set on all elements.

I've setup this [codesandbox](https://codesandbox.io/p/devbox/rxhpzy?file=%2Ftailwind.config.js%3A12%2C1) that hopefully demonstrates the issue. (Hopefully that works, let me know if not).

For reference, I'm also using the tailwind prefix option (i.e. append `tw-` to all classes) and the important selector modifier (i.e. everything is a descendant of a single selector) , but they weren't needed to reproduce this.

Let me know if you need any more clarification.

**Comment by Roman86** [comment]
ah, I see the version 15.2 in the issue title. According to [this info](https://caniuse.com/?search=%3Awhere) it should be supported. Can you try upgrading or another machine with 15.2?

Another option - I'm preparing the major release (actually only the readme update left) that allows the logic customization - so you will be able to try using it without `:where` also

**Comment by Roman86** [comment]
### Announcement!

v3 is available as beta now 💪

https://www.npmjs.com/package/tailwindcss-scoped-preflight/v/3.0.0-beta.3

```bash
npm i tailwindcss-scoped-preflight@next
```

I tested it with all the strategies - now it's flexible to cover any use case I believe.

Please check this out @PhilipHow 
If none of built-in strategies work for you (although `isolateInsideOfContainer` should work, it doesn't use `:where`) - you may play with your own.

**Comment by michaelpumo** [comment]
Thanks for this!

**Comment by Roman86** [comment]
if anybody can confirm the issue with details - please feel free to reopen. Seems to be working great. Btw, you can debug/customize the plugin logic in v3
