### ISSUE TITLE
How to make this work within vite-react app? 

### ISSUE THREAD

**Issue by berkerdemirer** [Roman86/tailwindcss-scoped-preflight#37]
Hey,

I am trying to ship a library and I don't want my library's preflight to clash with consumer app's styles. That's why I wanted to isolate everything. 

I added the tw config as referenced in the doc:

```  
plugins: [
    require('tailwindcss-animate'),
    scopedPreflightStyles({
      isolationStrategy: isolateInsideOfContainer('.twc'),
    }),
  ],
```

index.html:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/devicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Webshop search</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/demo.tsx"></script>
  </body>
</html>
```

But when I compile my CSS, I only see the comments for the preflight classes. Classes themselves are missing. Is there something else that I should be doing?

<img width="866" alt="image" src="https://github.com/user-attachments/assets/3f96a2d9-2a96-4412-915f-45ad1dc6dc15">

**Comment by berkerdemirer** [comment]
I had to add that classname to the wrapper div in one of my jsx.

**Comment by berkerdemirer** [comment]
Actually, it did not work as expected.. reopening for a discussion

**Comment by Roman86** [comment]
hi @berkerdemirer ! Did you get TailwindCSS working without a plugin? I guess you're missing the `content: ['**/*.html'],` param in your config

**Comment by Roman86** [comment]
another thing - Tailwind is HTML processor that is crawling your HTML files (kind of) - it generates only CSS used in your HTML. Probably since our preflight styles are customized (need that extra selector) they are filtered out if not found in HTML

**Comment by Roman86** [comment]
another suggestion - if you ship tailwind-styles components - you just make tailwind a peer dependency (host app should have it's own config with it's own opinion/policy about preflight styles), + some partial config for the host to extend with (if any custom stuff needed). So I wouldn't use this plugin on the library side at all

**Comment by berkerdemirer** [comment]
Hi, Roman,

The thing is, once I ship this package, it should be framework and setup-agnostic. It has to work when there is no tailwind configured in the target app. That's why I am compiling the CSS to import it later when I use this package.

Regarding adding HTML to the content array, you were right that I was missing it. But where exactly I should add the wrapper class inside the HTML? To body tag or?

**Comment by Roman86** [comment]
@berkerdemirer please check my suggestions. What do you think?

**Comment by Roman86** [comment]
hi @berkerdemirer ! A month passed since my reply. I'm closing it for now, please try what I suggested. I believe it should work. Feel free to re-open if it didn't

**Comment by stephenasuncionDEV** [comment]
Same thing happens to my vite-react app, missing preflight styles
