### ISSUE TITLE
Scoping won't apply styles from html and body selectors

### ISSUE THREAD

**Issue by mponizil** [Roman86/tailwindcss-scoped-preflight#4]
Thank you for spinning up this plugin!

It looks like we're just appending `:where(.twp,.twp *)` to all rules, which won't have any effect on the html or body rules (unless the selector is added to those, which defeats the purpose). In my case, it prevents a global `font-family` rule from applying within the scope.

I guess we'd need to add some logic that checks for html and body rules and just replaces them with `.twp`. Perhaps something like this could work:

```typescript
baseCssStyles.walkRules((rule) => {
  rule.selectors = rule.selectors.map((s) => {
    if (mode === 'except matched') {
      return `${s}:where(:not(${cssSelector} *))`;
    } else {
      if (['html', 'body'].includes(s)) {
        return cssSelector;
      } else {
        return`${s}:where(${cssSelector},${cssSelector} *)`;
      }
    }
  });
  rule.selector = rule.selectors.join(',\n');
});
```

Let me know if I've misunderstood anything, or if there's anything I can explain further. Thanks!

**Comment by Roman86** [comment]
@mponizil  thanks for reaching out and your feedback! I see the problem. You point is valid, but proposed fix may break some use cases. As the selector can be used not just for containers, but also for particular elements (utilizing the `:where` pseudo-class) making it possible to avoid any extra containers for your components. I think I'm missing another mode 'under matching' for your request - then I can convert html and body to that selector too.

Also, I'm going to release a major version where you have control over everything:
* selectors - full customization via callback - re-wrap preflight rules however needed;
* rules - CSS properties filter callback - remove what you don't want to happen;
  * if all rule's properties filtered out - the rule won't be generated at all;

Stay tuned 😉

**Comment by Roman86** [comment]
just released [v2.2.0-beta.0](https://github.com/Roman86/tailwindcss-scoped-preflight/compare/v2.1.1...v2.2.0-beta.0)
Please check if it does the trick for you @mponizil

**Comment by Roman86** [comment]
sorry, one more fix needed. I'll post the update

**Comment by Roman86** [comment]
ok, [v2.2.0-beta.1](https://github.com/Roman86/tailwindcss-scoped-preflight/compare/v2.1.1...v2.2.0-beta.1)
please check @mponizil

**Comment by Roman86** [comment]
due to late night fixes I forgot to build the bundle, releasing the v3 code in fact, which had broken things for all who tried 🙈 I hope nobody did.
So, this is the working version [v2.2.0-beta.2](https://github.com/Roman86/tailwindcss-scoped-preflight/compare/v2.1.0...v2.2.0-beta.2). Previous 2 betas deprecated. The `latest` tag reset to `v2.1.0`. Had to publish with  `beta` npm dist-tag, a lesson learned.

**Comment by Roman86** [comment]
### Announcement!

v3 is available as beta now 💪

https://www.npmjs.com/package/tailwindcss-scoped-preflight/v/3.0.0-beta.3

```bash
npm i tailwindcss-scoped-preflight@next
```

I tested it with all the strategies - now it's flexible to cover any use case I believe.

@mponizil
