### ISSUE TITLE
License for the package?

### ISSUE THREAD

**Issue by kennethormandy** [Roman86/tailwindcss-scoped-preflight#5]
Hi! Thanks for this package—I’m trying out the v3.0.0 beta and it’s working great.

I was wondering what the license is? You have ISC in the `package.json`, is that correct?

If you don’t mind adding a license file, that would be really helpful. Thanks!

**Comment by Roman86** [comment]
hi @kennethormandy and thanks for reaching out!
1. You're right, I should create that file.
2. To be honest I'm not sure about the actual license - ISC is just a default option that seems to be ok. If you want to suggest some other license type - please advise. Some examples to compare (and maybe follow) are welcome!

**Comment by Roman86** [comment]
@kennethormandy v3.0.5 is released, it includes the license file now

**Comment by kennethormandy** [comment]
Thanks for that!

I am not a lawyer, this is not legal advice, etc. I feel like MIT would be the natural choice since that’s how Tailwind is licensed.

That said, this works perfectly fine for me, and ISC is very, very similar.
