### ISSUE TITLE
Protecting the tailwind component from the outer styles and classes. 

### ISSUE THREAD

**Issue by azizChebbi** [Roman86/tailwindcss-scoped-preflight#64]
I'm working on a project of migrating an angularjs app to react+shadcn using a hybrid approach, where we start migrating from leaf nodes up to bigger components.
concerning the design, I have protected the angularjs from the tailwind preflight successfully, but the issue is that my react components (shadcn components) are impacted by styles used for angularjs components, also impacted by bootstrap styles, etc...
so is it possible to have a wrapper that protects the react components from outer classes ?
we tried so many approaches, but none of them worked perfectly.
just to mention, that in our case, we will never have angularjs inside react, always react starting from the leaf.

**Comment by Roman86** [comment]
Hi @azizChebbi ! What you ask is  nothing about tailwindcss or this plugin. Consider asking on stackoverflow for better help.
I can suggest you to use shadow dom - it has completely isolated styles scope. Or try isolating styles by using different wrappers with sass/scss
