### ISSUE TITLE
Error on Vite build when using Tailwind config in the application: `"readFileSync" is not exported by "__vite-browser-external"`

### ISSUE THREAD

**Issue by baffalop** [Roman86/tailwindcss-scoped-preflight#65]
**Describe the bug**

I'm using Tailwind with Vite, and also using some of my Tailwind theme values in javascript using `resolveConfig` and importing my Tailwind config in the application, as per https://tailwindcss.com/docs/configuration#referencing-in-java-script . When the plugin is added as part of this setup, it causes an error on build.

First Vite warns about externalised Node modules:
```
[plugin vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "[...]/node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

Followed by the error:
```
error during build:
node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs (3:9): "readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs".
file: [...]/node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs:3:9

1: import TailwindPlugin from 'tailwindcss/plugin.js';
2: import postcss from 'postcss';
3: import { readFileSync } from 'fs';
            ^
4: 
5: const optionsHandlerForIgnoreAndRemove = (selector, {

    at getRollupError (file:///[...]/node_modules/rollup/dist/es/shared/parseAst.js:558:41)
    at Module.error (file:///[...]/node_modules/rollup/dist/es/shared/parseAst.js:554:42)
    at Module.error (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:15613:29)
    at Module.traceVariable (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:16062:29)
    at ModuleScope.findVariable (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:13845:39)
    at ReturnValueScope.findVariable (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:5308:38)
    at FunctionBodyScope.findVariable (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:5308:38)
    at ReturnValueScope.findVariable (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:5308:38)
    at FunctionBodyScope.findVariable (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:5308:38)
    at Identifier.bind (file:///[...]/node_modules/rollup/dist/es/shared/node-entry.js:5091:40)
```

This is evidently because the plugin is written to be run in a Node context, but the evaluation of Tailwind config from the browser context is enough for Vite to try to compile all its dependencies.

**To Reproduce**
Code sandbox URL (any platform of your choice): https://stackblitz.com/edit/vitejs-vite-1ne1wu?file=src%2Fcomponents%2FToBeScoped.vue

Note that the application runs fine with `npm run dev`—and the `ToBeScoped` component includes an import of Tailwind config (to print the hex of a theme colour on the screen).

Running `npm run build` causes the error.

**Expected behaviour**

It might be reasonable to expect the application developer to find some strategy for pre-evaluating their Tailwind config to avoid the plugin being included in the frontend bundle. The [linked section of the Tailwind docs](https://tailwindcss.com/docs/configuration#referencing-in-java-script) offers a solution using Babel; for Vite I found [a solution using a virtual module](https://evomark.co.uk/development/making-your-tailwind-config-available-to-your-entire-application-with-vite/).

I mainly wanted to log this issue for the sake of future developers who run into the same issue, as it took us a good deal of effort to find the root cause. At the very least a note in the documentation might also help!

However, could the issue be avoided by splitting out a separate module for the actual work of reading and parsing the Preflight file, in such a way that Vite doesn't try to compile the Node import, or include more than is needed in the frontend build?

**Additional context**

The error was originally logged by my colleague in https://github.com/Roman86/tailwindcss-scoped-preflight/issues/63 but this was before we understood that the root cause was use of the Tailwind config at runtime. I thought it best to log as a new issue with full details.

**Comment by Roman86** [comment]
I had exactly same issue and it's quite simple to resolve as I mentioned above. If you need more assistance - don't hesitate to continue the thread

**Comment by baffalop** [comment]
@Roman86 I don't know why I didn't think of that! In any case, the virtual module solution worked for me. Like I said, I mainly wanted to log the issue so future users know what the error means.
